//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Справочник_Книг.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Справочник_книгEntities : DbContext
    {
        private static Справочник_книгEntities _context;
        public static Справочник_книгEntities GetContext()
        {
            if (_context == null)
            {
                _context = new Справочник_книгEntities();
            }
            return _context;
        }
        public Справочник_книгEntities()
            : base("name=Справочник_книгEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Авторы> Авторы { get; set; }
        public DbSet<Жанры> Жанры { get; set; }
        public DbSet<Книги> Книги { get; set; }
        public DbSet<Оценки> Оценки { get; set; }
        public DbSet<Пользователи> Пользователи { get; set; }
        public DbSet<Прочитанные_Книги> Прочитанные_Книги { get; set; }
    }
}
