//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Справочник_Книг.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Авторы
    {
        public Авторы()
        {
            this.Книги = new HashSet<Книги>();
        }
    
        public int ID_Автора { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public Nullable<System.DateTime> Дата_Рождения { get; set; }
        public string Страна { get; set; }
        public string История { get; set; }
    
        public virtual ICollection<Книги> Книги { get; set; }
    }
}
