//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Справочник_Книг.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Книги
    {
        public Книги()
        {
            this.Оценки = new HashSet<Оценки>();
            this.Прочитанные_Книги = new HashSet<Прочитанные_Книги>();
        }
    
        public int ID_Книги { get; set; }
        public string Название { get; set; }
        public int ID_Автора { get; set; }
        public int ID_Жанра { get; set; }
        public Nullable<int> Год_Издания { get; set; }
        public string Описание { get; set; }
    
        public virtual Авторы Авторы { get; set; }
        public virtual Жанры Жанры { get; set; }
        public virtual ICollection<Оценки> Оценки { get; set; }
        public virtual ICollection<Прочитанные_Книги> Прочитанные_Книги { get; set; }
    }
}
