//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Справочник_Книг.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователи
    {
        public Пользователи()
        {
            this.Оценки = new HashSet<Оценки>();
            this.Прочитанные_Книги = new HashSet<Прочитанные_Книги>();
        }
    
        public int ID_Пользователя { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public string Электронная_Почта { get; set; }
        public string Телефон { get; set; }
    
        public virtual ICollection<Оценки> Оценки { get; set; }
        public virtual ICollection<Прочитанные_Книги> Прочитанные_Книги { get; set; }
    }
}
