//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Справочник_Книг.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Прочитанные_Книги
    {
        public int ID_Списка { get; set; }
        public int ID_Пользователя { get; set; }
        public int ID_Книги { get; set; }
        public Nullable<System.DateTime> Дата_Прочтения { get; set; }
    
        public virtual Книги Книги { get; set; }
        public virtual Пользователи Пользователи { get; set; }
    }
}
