//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Университет.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Категория
    {
        public Категория()
        {
            this.Преподы = new HashSet<Преподы>();
        }
    
        public string Категория1 { get; set; }
        public int ID_категории { get; set; }
        public Nullable<double> оклад { get; set; }
    
        public virtual ICollection<Преподы> Преподы { get; set; }
    }
}
