//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Университет.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Преподы
    {
        public Преподы()
        {
            this.Проведение_предмета = new HashSet<Проведение_предмета>();
        }
    
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public Nullable<int> ID_категории { get; set; }
        public int ID_препода { get; set; }
        public string улица { get; set; }
        public string дом { get; set; }
        public Nullable<int> кв { get; set; }
    
        public virtual Категория Категория { get; set; }
        public virtual ICollection<Проведение_предмета> Проведение_предмета { get; set; }
    }
}
