//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Университет.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Предмет
    {
        public Предмет()
        {
            this.Проведение_предмета = new HashSet<Проведение_предмета>();
        }
    
        public string Название_предмета { get; set; }
        public Nullable<int> ID_Цикла { get; set; }
        public Nullable<int> Часы { get; set; }
        public int ID_предмета { get; set; }
    
        public virtual Цикл Цикл { get; set; }
        public virtual ICollection<Проведение_предмета> Проведение_предмета { get; set; }
    }
}
