//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magnit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        public int ID_заказа { get; set; }
        public int ID_пользователя { get; set; }
        public int ID_товара { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<System.TimeSpan> Время { get; set; }
        public string Колличество { get; set; }
    
        public virtual Пользователь Пользователь { get; set; }
        public virtual Товар Товар { get; set; }
    }
}
