//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magnit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователь
    {
        public Пользователь()
        {
            this.Заказ = new HashSet<Заказ>();
        }
    
        public int ID_пользователя { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Номер_телефона { get; set; }
        public string пол { get; set; }
        public string электронная_почта { get; set; }
        public Nullable<System.DateTime> Возраст { get; set; }
        public string Пароль { get; set; }
    
        public virtual ICollection<Заказ> Заказ { get; set; }
    }
}
