//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magnit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Производитель
    {
        public Производитель()
        {
            this.Товар = new HashSet<Товар>();
        }
    
        public int ID_производителя { get; set; }
        public string Название { get; set; }
        public string Адрес { get; set; }
    
        public virtual ICollection<Товар> Товар { get; set; }
    }
}
