//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magnit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товар
    {
        public Товар()
        {
            this.Заказ = new HashSet<Заказ>();
        }
    
        public int ID_товара { get; set; }
        public int ID_производителя { get; set; }
        public int ID_категории { get; set; }
        public string название { get; set; }
        public string описание { get; set; }
    
        public virtual ICollection<Заказ> Заказ { get; set; }
        public virtual Категория Категория { get; set; }
        public virtual Производитель Производитель { get; set; }
    }
}
