//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Steam.Model
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    public partial class User
    {
        public User()
        {
            this.Колекция = new HashSet<Колекция>();
            this.Отзывы = new HashSet<Отзывы>();
        }
    
        public int ID_User { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Фото { get; set; }
        public string Ник { get; set; }
        public Nullable<System.DateTime> Год_рождения { get; set; }
        public string Адрес { get; set; }
    
        public virtual ICollection<Колекция> Колекция { get; set; }
        public virtual ICollection<Отзывы> Отзывы { get; set; }
        public string GetPhoto
        {
            get
            {
                if (string.IsNullOrWhiteSpace(Фото))
                    return null;

                string fullPath = System.IO.Path.Combine(@"C:\Users\User\Documents\STUDY\УП\Steam\Фото", Фото.Trim());
                if (File.Exists(fullPath))
                {
                    // Преобразуем абсолютный путь в Uri-совместимый формат
                    return new Uri(fullPath).AbsoluteUri;
                }
                return null;
            }
        }
    }
}
