//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Steam.Model
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Windows.Media.Imaging;
    using System.Windows.Media;

    public partial class Игра
    {
        public Игра()
        {
            this.Колекция = new HashSet<Колекция>();
            this.Контент = new HashSet<Контент>();
            this.Отзывы = new HashSet<Отзывы>();
        }
    
        public int ID_Игры { get; set; }
        public string Название { get; set; }
        public string Локализация { get; set; }
        public System.DateTime Дата_релиза { get; set; }
        public System.DateTime Дата_региона { get; set; }
        public string Платформы { get; set; }
        public string Жанры { get; set; }
        public int ID_Разработчика { get; set; }
        public int ID_Издателя { get; set; }
        public string Возростной_рейтинг { get; set; }
        public string Системные_требования { get; set; }
        public string Описание { get; set; }
        public int Среднее_время { get; set; }
        public int ID_Типа_издания { get; set; }
        public int ID_Статуса { get; set; }
        public string Фото { get; set; }
        public string GetPhoto
        {
            get
            {
                if (string.IsNullOrWhiteSpace(Фото))
                    return null;

                string fullPath = System.IO.Path.Combine(@"C:\Users\User\Documents\STUDY\УП\Steam\Фото\", Фото.Trim());
                if (File.Exists(fullPath))
                {
                    // Преобразуем абсолютный путь в Uri-совместимый формат
                    return new Uri(fullPath).AbsoluteUri;
                }
                return null;
            }
        }
        
        public virtual Издатель Издатель { get; set; }
        public virtual Разработчик Разработчик { get; set; }
        public virtual Статус Статус { get; set; }
        public virtual Тип_Издания Тип_Издания { get; set; }
        public virtual ICollection<Колекция> Колекция { get; set; }
        public virtual ICollection<Контент> Контент { get; set; }
        public virtual ICollection<Отзывы> Отзывы { get; set; }
    }
}
