//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Steam.Model
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    public partial class Издатель
    {
        public Издатель()
        {
            this.Игра = new HashSet<Игра>();
        }
    
        public int ID_Издателя { get; set; }
        public string Название { get; set; }
        public string Страна { get; set; }
        public string Год { get; set; }
        public string Фото { get; set; }
    
        public virtual ICollection<Игра> Игра { get; set; }
        public string GetPhoto
        {
            get
            {
                if (string.IsNullOrWhiteSpace(Фото))
                    return null;

                string fullPath = System.IO.Path.Combine(@"C:\Users\User\Documents\STUDY\УП\Steam\Издатель", Фото.Trim());
                if (File.Exists(fullPath))
                {
                    // Преобразуем абсолютный путь в Uri-совместимый формат
                    return new Uri(fullPath).AbsoluteUri;
                }
                return null;
            }
        }
    }
}
