//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Steam.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Контент
    {
        public int ID_Контента { get; set; }
        public int ID_Игры { get; set; }
        public string Название { get; set; }
        public string Тип_контента { get; set; }
        public string Описание { get; set; }
        public System.DateTime Дата { get; set; }
        public string Цена { get; set; }
    
        public virtual Игра Игра { get; set; }
    }
}
