//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Steam.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Колекция
    {
        public int ID_Колекции { get; set; }
        public int ID_Игры { get; set; }
        public int ID_User { get; set; }
        public int ID_Сатуса_прохождения { get; set; }
        public decimal Часы_игры { get; set; }
        public Nullable<decimal> Оценка { get; set; }
        public string Пользовательские_тэги { get; set; }
    
        public virtual User User { get; set; }
        public virtual Игра Игра { get; set; }
        public virtual Статус_прохождения Статус_прохождения { get; set; }
    }
}
