//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Steam.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Отзывы
    {
        public int ID_Отзыва { get; set; }
        public int ID_Игры { get; set; }
        public int ID_User { get; set; }
        public string Тип_автора { get; set; }
        public string Текст_рецензии { get; set; }
        public Nullable<int> Рейтинг { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<int> Лайки { get; set; }
        public Nullable<int> Дизлайки { get; set; }
    
        public virtual User User { get; set; }
        public virtual Игра Игра { get; set; }
    }
}
