//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Steam.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Разработчик
    {
        public Разработчик()
        {
            this.Игра = new HashSet<Игра>();
        }
    
        public int ID_Разработчика { get; set; }
        public string Название { get; set; }
        public string Страна { get; set; }
        public string Год { get; set; }
        public string специализация { get; set; }
    
        public virtual ICollection<Игра> Игра { get; set; }
    }
}
