//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Клиенты = new HashSet<Клиенты>();
            this.Сотрудник = new HashSet<Сотрудник>();
        }
    
        public int ID_user { get; set; }
        public string Номер_телефона { get; set; }
        public string Пароль { get; set; }
        public int ID_роли { get; set; }
    
        public virtual Роли Роли { get; set; }
        public virtual ICollection<Клиенты> Клиенты { get; set; }
        public virtual ICollection<Сотрудник> Сотрудник { get; set; }
    }
}
