//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class История_посещений
    {
        public int ID_истории { get; set; }
        public int ID_времени { get; set; }
        public int ID_питомца { get; set; }
        public System.TimeSpan Время_записи { get; set; }
        public string Стоимость { get; set; }
        public Nullable<int> Статус_записи { get; set; }
        public string Коментарий { get; set; }
        public string Скан { get; set; }
        public string Скан_2 { get; set; }
        public string Скан_3 { get; set; }
    
        public virtual Питомцы Питомцы { get; set; }
        public virtual Рабочее_время Рабочее_время { get; set; }
        public virtual Статус_записи Статус_записи1 { get; set; }
    }
}
