//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Models
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class Категория_услуг
    {
        public Категория_услуг()
        {
            this.Услуги = new HashSet<Услуги>();
        }
    
        public int ID_Категории { get; set; }
        public string Название { get; set; }
        public string Описание_услуг { get; set; }
        public string Фото { get; set; }
        public string Цена { get; set; }
    
        public virtual ICollection<Услуги> Услуги { get; set; }

        public string GetPhoto
        {
            get
            {
                if (Фото is null)
                    return null;
                return Directory.GetCurrentDirectory() + @"C:\Users\User\Documents\STUDY\УП\WpfApp2\Иконки\" + Фото.Trim();
            }
        }
    }
}
