//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Клиенты
    {
        public Клиенты()
        {
            this.Питомцы = new HashSet<Питомцы>();
        }
    
        public int ID_клиента { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Номер_телефона { get; set; }
        public string Электронная_почта { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public string Город { get; set; }
        public string Улица { get; set; }
        public string Дом { get; set; }
        public string Квартира { get; set; }
        public int ID_user { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Питомцы> Питомцы { get; set; }
    }
}
