//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Models
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    
    public partial class Питомцы
    {
        public Питомцы()
        {
            this.История_посещений = new HashSet<История_посещений>();
        }
    
        public int ID_питомца { get; set; }
        public string Кличка { get; set; }
        public int ID_вида { get; set; }
        public string Порода { get; set; }
        public string Пол { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public string Вес { get; set; }
        public string Рост { get; set; }
        public string Группа_крови { get; set; }
        public string Возраст { get; set; }
        public string Аллергии { get; set; }
        public string Заболевания_хронический { get; set; }
        public string Фото { get; set; }
        public int ID_клиента { get; set; }
    
        public virtual ICollection<История_посещений> История_посещений { get; set; }
        public virtual Категория_питомца Категория_питомца { get; set; }
        public virtual Клиенты Клиенты { get; set; }
        public string GetPhoto
        {
            get
            {
                if (string.IsNullOrWhiteSpace(Фото))
                    return null;

                string fullPath = System.IO.Path.Combine(@"C:\Users\User\Documents\STUDY\УП\WpfApp2\Фото\", Фото.Trim());
                if (File.Exists(fullPath))
                {
                    // Преобразуем абсолютный путь в Uri-совместимый формат
                    return new Uri(fullPath).AbsoluteUri;
                }
                return null;
            }
        }
    }
}
