//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Рабочее_время
    {
        public Рабочее_время()
        {
            this.История_посещений = new HashSet<История_посещений>();
        }
    
        public int ID_времени { get; set; }
        public int ID_сотрудника { get; set; }
        public int ID_услуги { get; set; }
        public System.DateTime Дата { get; set; }
        public System.TimeSpan Время_Начало { get; set; }
        public Nullable<System.TimeSpan> Время_завершения { get; set; }
    
        public virtual ICollection<История_посещений> История_посещений { get; set; }
        public virtual Сотрудник Сотрудник { get; set; }
        public virtual Услуги Услуги { get; set; }
    }
}
