//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Models
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    public partial class Сотрудник
    {
        public Сотрудник()
        {
            this.Рабочее_время = new HashSet<Рабочее_время>();
        }
    
        public int ID_сотрудника { get; set; }
        public int ID_user { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Образование { get; set; }
        public string Должность { get; set; }
        public string Должность_2 { get; set; }
        public string Должность_3 { get; set; }
        public string Опыт { get; set; }
        public string Фото { get; set; }
        public string ФИО => $"{Фамилия} {Имя} {Отчество}";
        public Nullable<int> ID_статуса { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Рабочее_время> Рабочее_время { get; set; }
        public virtual Статус Статус { get; set; }
        public string GetPhoto
        {
            get
            {
                if (Фото is null)
                    return null;
                return Directory.GetCurrentDirectory() + @"C:\Users\User\Documents\STUDY\УП\WpfApp2\Фото\" + Фото.Trim();
            }
        }
    }
}
