//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Услуги
    {
        public Услуги()
        {
            this.Рабочее_время = new HashSet<Рабочее_время>();
        }
    
        public int ID_услуги { get; set; }
        public string Название { get; set; }
        public string Стоимость { get; set; }
        public string Длительность { get; set; }
        public int ID_категории { get; set; }
    
        public virtual Категория_услуг Категория_услуг { get; set; }
        public virtual ICollection<Рабочее_время> Рабочее_время { get; set; }

    }
}
