//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Тур_агенство.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Города
    {
        public Города()
        {
            this.Туры = new HashSet<Туры>();
        }
    
        public int Id { get; set; }
        public string Название { get; set; }
        public Nullable<int> СтранаId { get; set; }
    
        public virtual Страны Страны { get; set; }
        public virtual ICollection<Туры> Туры { get; set; }
    }
}
