//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Тур_агенство.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Клиенты
    {
        public Клиенты()
        {
            this.Бронирования = new HashSet<Бронирования>();
            this.Рекомендации = new HashSet<Рекомендации>();
        }
    
        public int Id { get; set; }
        public string ФИО { get; set; }
        public string ЭлектроннаяПочта { get; set; }
        public string Телефон { get; set; }
    
        public virtual ICollection<Бронирования> Бронирования { get; set; }
        public virtual ICollection<Рекомендации> Рекомендации { get; set; }
    }
}
