//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Тур_агенство.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Рекомендации
    {
        public int Id { get; set; }
        public Nullable<int> КлиентId { get; set; }
        public Nullable<int> ТурId { get; set; }
        public string Причина { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
        public virtual Туры Туры { get; set; }
    }
}
