//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Тур_агенство.model
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class Туры
    {
        public Туры()
        {
            this.Бронирования = new HashSet<Бронирования>();
            this.Рекомендации = new HashSet<Рекомендации>();
        }
    
        public int Id { get; set; }
        public string Название { get; set; }
        public string Описание { get; set; }
        public decimal Цена { get; set; }
        public Nullable<System.DateTime> ДатаНачала { get; set; }
        public Nullable<System.DateTime> ДатаОкончания { get; set; }
        public Nullable<int> ГородId { get; set; }
        public string Фото { get; set; }
    
        public virtual ICollection<Бронирования> Бронирования { get; set; }
        public virtual Города Города { get; set; }
        public virtual ICollection<Рекомендации> Рекомендации { get; set; }
        public string GetFhoto
        {
            get
            {
                if (Фото is null)
                    return null;
                return Directory.GetCurrentDirectory() + @"\Images\" + Фото.Trim();
            }
        }
    }
}
