//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class История_покупок
    {
        public int ID_Истории_покупок { get; set; }
        public Nullable<int> ID_Товара { get; set; }
        public int ID_Проведенные_услуги { get; set; }
        public int Кол_товара { get; set; }
        public string Дата_время { get; set; }
        public int Итоговая_сумма { get; set; }
        public string Вид_оплаты { get; set; }
    
        public virtual Проведенные_услуги Проведенные_услуги { get; set; }
        public virtual Товар Товар { get; set; }
    }
}
