//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Категории
    {
        public Категории()
        {
            this.Сотрудник = new HashSet<Сотрудник>();
            this.Услуги = new HashSet<Услуги>();
        }
    
        public int ID_Категории { get; set; }
        public string Категория { get; set; }
        public int Коэф_оплаты { get; set; }
    
        public virtual ICollection<Сотрудник> Сотрудник { get; set; }
        public virtual ICollection<Услуги> Услуги { get; set; }
    }
}
