//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Клиент
    {
        public Клиент()
        {
            this.Проведенные_услуги = new HashSet<Проведенные_услуги>();
        }
    
        public int ID_Клиента { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Телефон { get; set; }
        public string Email { get; set; }
        public System.DateTime Дата_рождения { get; set; }
        public string Пол_клиента { get; set; }
        public System.DateTime Дата_регистрации { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Проведенные_услуги> Проведенные_услуги { get; set; }
    }
}
