//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Комплект
    {
        public int ID_Комплекта { get; set; }
        public int ID_Товара1 { get; set; }
        public int ID_Товара2 { get; set; }
    
        public virtual Товар Товар { get; set; }
        public virtual Товар Товар1 { get; set; }
    }
}
