//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Наличие_товара
    {
        public int ID_Наличие { get; set; }
        public int ID_Товара { get; set; }
        public int ID_Склада { get; set; }
        public int Кол_товара { get; set; }
    
        public virtual Склад Склад { get; set; }
        public virtual Товар Товар { get; set; }
    }
}
