//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Проведенные_услуги
    {
        public Проведенные_услуги()
        {
            this.История_покупок = new HashSet<История_покупок>();
            this.Продажи_услуг = new HashSet<Продажи_услуг>();
        }
    
        public int ID_Проведенных_услуг { get; set; }
        public int ID_Клиента { get; set; }
        public int ID_Услуги { get; set; }
        public System.DateTime Начало_оказания_услуги { get; set; }
        public string Статус { get; set; }
        public int ID_Сотрудника { get; set; }
        public string Коментарий_Сотрудника { get; set; }
    
        public virtual ICollection<История_покупок> История_покупок { get; set; }
        public virtual Клиент Клиент { get; set; }
        public virtual Сотрудник Сотрудник { get; set; }
        public virtual Услуги Услуги { get; set; }
        public virtual ICollection<Продажи_услуг> Продажи_услуг { get; set; }
    }
}
