//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Рабочее_время
    {
        public int ID_Рабочее_время { get; set; }
        public int ID_Сотрудника { get; set; }
        public int ID_Услуги { get; set; }
        public string Рабочее_время1 { get; set; }
    
        public virtual Сотрудник Сотрудник { get; set; }
        public virtual Услуги Услуги { get; set; }
    }
}
