//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сезонные_товары
    {
        public int ID_Сезонного_товара { get; set; }
        public string Название { get; set; }
        public int ID_Товара { get; set; }
        public int ID_Сезона { get; set; }
    
        public virtual Сезон Сезон { get; set; }
        public virtual Товар Товар { get; set; }
    }
}
