//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудник
    {
        public Сотрудник()
        {
            this.Проведенные_услуги = new HashSet<Проведенные_услуги>();
            this.Рабочее_время = new HashSet<Рабочее_время>();
        }
    
        public int ID_Сотрудника { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Серия_номер { get; set; }
        public string Пол { get; set; }
        public System.DateTime Дата_рождения { get; set; }
        public int ID_Категории { get; set; }
        public string Login_s { get; set; }
        public string Password_s { get; set; }
    
        public virtual Категории Категории { get; set; }
        public virtual Категория Категория { get; set; }
        public virtual ICollection<Проведенные_услуги> Проведенные_услуги { get; set; }
        public virtual ICollection<Рабочее_время> Рабочее_время { get; set; }
    }
}
