//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товар
    {
        public Товар()
        {
            this.История_покупок = new HashSet<История_покупок>();
            this.Комплект = new HashSet<Комплект>();
            this.Комплект1 = new HashSet<Комплект>();
            this.Наличие_товара = new HashSet<Наличие_товара>();
            this.Сезонные_товары = new HashSet<Сезонные_товары>();
        }
    
        public int ID_Товара { get; set; }
        public int ID_Категории_товара { get; set; }
        public Nullable<int> Стоимость { get; set; }
        public string Наименование_Товара { get; set; }
        public string Описание { get; set; }
        public string Вес { get; set; }
        public Nullable<int> Ширина { get; set; }
        public Nullable<int> Высота { get; set; }
        public Nullable<int> Длинна { get; set; }
        public string Производитель { get; set; }
        public string Доп_фото { get; set; }
        public string Актуальность { get; set; }
    
        public virtual ICollection<История_покупок> История_покупок { get; set; }
        public virtual Категория_товара Категория_товара { get; set; }
        public virtual ICollection<Комплект> Комплект { get; set; }
        public virtual ICollection<Комплект> Комплект1 { get; set; }
        public virtual ICollection<Наличие_товара> Наличие_товара { get; set; }
        public virtual ICollection<Сезонные_товары> Сезонные_товары { get; set; }
    }
}
