//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Услуги
    {
        public Услуги()
        {
            this.Проведенные_услуги = new HashSet<Проведенные_услуги>();
            this.Рабочее_время = new HashSet<Рабочее_время>();
            this.Сканы = new HashSet<Сканы>();
        }
    
        public int ID_Услуги { get; set; }
        public Nullable<int> ID_Изабражения { get; set; }
        public string Наименование_услуги { get; set; }
        public string Продолжительность { get; set; }
        public int Стоимость { get; set; }
        public double Скидка { get; set; }
        public int ID_Категории { get; set; }
    
        public virtual Изображения Изображения { get; set; }
        public virtual Категории Категории { get; set; }
        public virtual ICollection<Проведенные_услуги> Проведенные_услуги { get; set; }
        public virtual ICollection<Рабочее_время> Рабочее_время { get; set; }
        public virtual ICollection<Сканы> Сканы { get; set; }
    }
}
