//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Журнал
    {
        public int Id_журнала { get; set; }
        public int Id_клиента { get; set; }
        public string Действие { get; set; }
        public System.DateTime Дата_и_время { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
    }
}
