//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Клиенты
    {
        public Клиенты()
        {
            this.Журнал = new HashSet<Журнал>();
            this.Посещения = new HashSet<Посещения>();
        }
    
        public int Id_клиента { get; set; }
        public string Логин { get; set; }
        public string Email { get; set; }
        public System.DateTime Дата_регистрации { get; set; }
        public Nullable<System.DateTime> Последний_вход { get; set; }
    
        public virtual ICollection<Журнал> Журнал { get; set; }
        public virtual ICollection<Посещения> Посещения { get; set; }
    }
}
