//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Посещения
    {
        public int Id_посещений { get; set; }
        public int Id_клиента { get; set; }
        public int Id_тренировки { get; set; }
        public System.DateTime Дата_записи { get; set; }
        public string Статус { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
        public virtual Тренировки Тренировки { get; set; }
    }
}
