//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Тренировки
    {
        public Тренировки()
        {
            this.Посещения = new HashSet<Посещения>();
            this.Рекомендации = new HashSet<Рекомендации>();
            this.Рекомендации1 = new HashSet<Рекомендации>();
        }
    
        public int Id_тренеровки { get; set; }
        public string Название { get; set; }
        public string Тип { get; set; }
        public string Тренер { get; set; }
        public System.DateTime Время_проведения { get; set; }
        public string Уникальный_код { get; set; }
        public Nullable<int> Id_филиала { get; set; }
    
        public virtual ICollection<Посещения> Посещения { get; set; }
        public virtual ICollection<Рекомендации> Рекомендации { get; set; }
        public virtual ICollection<Рекомендации> Рекомендации1 { get; set; }
        public virtual Филиалы Филиалы { get; set; }
    }
}
