//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Филиалы
    {
        public Филиалы()
        {
            this.Тренировки = new HashSet<Тренировки>();
        }
    
        public int Id_филиала { get; set; }
        public string Название { get; set; }
        public string Адрес { get; set; }
        public string Контактный_телефон { get; set; }
    
        public virtual ICollection<Тренировки> Тренировки { get; set; }
    }
}
