//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Учебное_Заведение.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оценки
    {
        public int ID_Оценки { get; set; }
        public int ID_Студента { get; set; }
        public int ID_Предмета { get; set; }
        public int Оценка { get; set; }
        public System.DateTime Дата { get; set; }
        public int ID_Преподавателя { get; set; }
    
        public virtual Предметы Предметы { get; set; }
        public virtual Преподаватели Преподаватели { get; set; }
        public virtual Студенты Студенты { get; set; }
    }
}
