//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Учебное_Заведение.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователи
    {
        public Пользователи()
        {
            this.Преподаватели = new HashSet<Преподаватели>();
            this.Студенты = new HashSet<Студенты>();
        }
    
        public int ID_Пользователя { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public string Роль { get; set; }
    
        public virtual ICollection<Преподаватели> Преподаватели { get; set; }
        public virtual ICollection<Студенты> Студенты { get; set; }
    }
}
