//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Учебное_Заведение.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Преподаватели
    {
        public Преподаватели()
        {
            this.Оценки = new HashSet<Оценки>();
            this.Посещаемость = new HashSet<Посещаемость>();
            this.Предметы = new HashSet<Предметы>();
        }
    
        public int ID_Преподавателя { get; set; }
        public string ФИО { get; set; }
        public int ID_Пользователя { get; set; }
    
        public virtual ICollection<Оценки> Оценки { get; set; }
        public virtual Пользователи Пользователи { get; set; }
        public virtual ICollection<Посещаемость> Посещаемость { get; set; }
        public virtual ICollection<Предметы> Предметы { get; set; }
    }
}
