//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Учебное_Заведение.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Предметы
    {
        public Предметы()
        {
            this.Оценки = new HashSet<Оценки>();
            this.Посещаемость = new HashSet<Посещаемость>();
            this.Расписание = new HashSet<Расписание>();
        }
    
        public int ID_Предмета { get; set; }
        public string Название_Предмета { get; set; }
        public int ID_Преподавателя { get; set; }
    
        public virtual ICollection<Оценки> Оценки { get; set; }
        public virtual ICollection<Посещаемость> Посещаемость { get; set; }
        public virtual Преподаватели Преподаватели { get; set; }
        public virtual ICollection<Расписание> Расписание { get; set; }
    }
}
