//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Учебное_Заведение.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Расписание
    {
        public int ID_Записи { get; set; }
        public int ID_Группы { get; set; }
        public string День_Недели { get; set; }
        public int Номер_Пары { get; set; }
        public int ID_Предмета { get; set; }
        public string Аудитория { get; set; }
    
        public virtual Группы Группы { get; set; }
        public virtual Предметы Предметы { get; set; }
    }
}
